### PR TITLE
add an is_initialized method to the fortran client

### PR DESCRIPTION
**Pull request by jedwards4b**
Add a method to fortran client to check if client%initialize has already been called.

### CODE REVIEW

**Review by ashao — APPROVED** [review]
This checks out on my machine and is a useful safety check to avoid instantiating multiple instances of the client unnecessarily. This is also needed to support the use of SmartRedis in both the NUOPC driver and standalone MOM6.

Could one of @al-rigazzi , @Spartee , @mellis13 check to ensure that it works on your internal machines as well?

**Comment by mellis13** [comment]
@ashao I'll take a look and make sure this passes on our internal machines

**Review by billschereriii — CHANGES_REQUESTED** [review]
Change looks reasonable and implementation is correct. However, should add a test case to attempt duplicate initialization and to validate that is_initialized is returning what we expect it to

**Comment by jedwards4b** [comment]
@billschereriii thank you for the review, I have added a test as requested.

**Comment by billschereriii** [comment]
Update looks good to me

**Review by billschereriii — APPROVED** [review]

**Comment by billschereriii** [comment]
merged

**Pull request merged**
