### PR TITLE
Updated Python API summary

### PR DESCRIPTION
**Pull request by billschereriii**
Update the Python API summary to include all the new methods we've added

### CODE REVIEW

**Comment by billschereriii** [comment]
Still outstanding: LogContext and Logger APIs

**Comment by billschereriii** [comment]
I believe that this PR is complete now but need to validate that the updates compile with Sphinx

**Review by ashao — APPROVED** [review]
Can confirm that the documentation compiles and displays properly. See below. Thank you for fixing this up @billschereriii 

image


image

**Review by al-rigazzi — APPROVED** [review]
LGTM! Thanks for this great user-friendliness improvement!

**Pull request merged**
