### PR TITLE
Fix multigpu set_model

### PR DESCRIPTION
**Pull request by al-rigazzi**
This PR fixes what seems to be a bug in setting the model for multiple GPUs.

### CODE REVIEW

**Review by ashao — APPROVED** [review]
Nice catch!

**Review by billschereriii — APPROVED** [review]
Thanks for catching this! I confirmed that the other 3 call sites (here and in RedisCluster.cpp) were correct already.

**Comment by billschereriii** [comment]
Please update the change log!

**Comment by al-rigazzi** [comment]
Updated - and fixed - the changelog!

**Pull request merged**
