### PR TITLE
Remove ParamSpec as Runtime Dep

### PR DESCRIPTION
**Pull request by MattToast**
Does NOT add typing extensions to SR run deps
Remove unused import
Turn all ParamSpec usage into forward refs

### CODE REVIEW

**Comment by billschereriii** [comment]
Looks good, but please update the changelog

**Comment by MattToast** [comment]
Good catch!

**Review by billschereriii — APPROVED** [review]
LGTM, just need a changelog update

**Review by ashao — APPROVED** [review]
Thanks for tracking that down so quickly. Make sure you add to the changelog!

**Comment by MattToast** [comment]
Closing this PR as it causes conficts with TF2.6.2 in SmartSim. Will put up a different fix

**Pull request merged**
